name: Tests in Ubuntu with Gold
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('.github/workflows/ubuntu-gold.yml') }}

      - uses: actions/setup-haskell@v1.1
        with:
          enable-stack: true

      - run: echo ::add-path::~/.local/bin

      - name: Install Idris by Stack
        run: |
          sudo apt install binutils-gold
          stack install idris-1.3.3 --ghc-options --with-ld=ld.gold

      - name: Run tests
        run: |
          idris --testpkg ether-momonga.ipkg
