name: Tests in Ubuntu with Gold
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: '8.10.2'
          enable-stack: true
          stack-version: 'latest'
      - name: Install Idris by Stack
        run: |
          sudo apt install binutils-gold
          stack install idris --ghc-options --with-ld=ld.gold
      - name: Run tests
        run: |
          idris --testpkg ether-momonga.ipkg
