name: Tests in Ubuntu with Gold
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Stack
        run: |
          curl -sSL https://get.haskellstack.org/ | sh
      - name: Install Idris by Cabal
        run: |
          sudo apt install binutils-gold
          stack install idris --ghc-options --with-ld=ld.gold
      - name: Run tests
        run: |
          idris --testpkg ether-momonga.ipkg
